name: Build CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build_job:
    name: Build (Unit-tests)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      - name: install cocoapods-generate
        run: sudo gem install cocoapods-generate
      - name: Build
        run: ./gradlew build