name: Build CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build_job:
    name: Build (Unit-tests)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      - name: Build
        run: ./gradlew build
      - name: Start SSH session
        if: ${{ failure() }}
        run: ./.github/scripts/ngrok-debug-ssh.sh
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
      - name: Don't kill instace
        if: ${{ failure() }}
        run: sleep 1h