name: Build CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build_job:
    name: Build (Unit-tests)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      - name: Build
        id: build_step_id
        continue-on-error: true
        run: ./gradlew build
      - name: First retry
        id: retry_step_id_1
        if: steps.build_step_id.outcome=='failure'
        continue-on-error: true
        run: ./gradlew build
      - name: Second retry
        id: retry_step_id_2
        if: steps.retry_step_id_1.outcome=='failure'
        continue-on-error: true
        run: ./gradlew build
      - name: Third retry
        id: retry_step_id_3
        if: steps.retry_step_id_2.outcome=='failure'
        continue-on-error: true
        run: ./gradlew build