name: Build & Publish CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_unit_test_publish_job:
    name: Build -> Unit-test -> Publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      - name: Build & Publish
        run: ./gradlew build publishAllPublicationsToSonatypeRepository
